version: '3'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - DEBUG=1
      - USE_SSL=0
      - SERVICES=s3
    ports:
      - "4566:4566"
