POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
  "name": "My Product",
  "price": 100.00
}

###

GET http://localhost:8000/products/1eaf5710-99aa-4662-a051-b2c689cde293 HTTP/1.1

###

PUT http://localhost:8000/products/1eaf5710-99aa-4662-a051-b2c689cde293
Content-Type: application/json

{
  "name": "My Product 2",
  "price": 100.10
}