version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672" # Porta padrão para o protocolo AMQP
      - "15672:15672" # Porta para a interface de gerenciamento do RabbitMQ (usuário: guest, senha: guest)
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/

